# Generated by Django 5.0.6 on 2026-04-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="allow_decimal",
            field=models.BooleanField(
                default=False,
                help_text="Allow selling fractional quantities e.g. 0.5 kg",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("piece", "Piece"),
                    ("kg", "Kilogram (kg)"),
                    ("g", "Gram (g)"),
                    ("ltr", "Litre (ltr)"),
                    ("ml", "Millilitre (ml)"),
                    ("pkt", "Packet (pkt)"),
                    ("box", "Box"),
                    ("dozen", "Dozen"),
                    ("bottle", "Bottle"),
                ],
                default="piece",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
